
SET SQL_MODE = "NO_AUTO_VALUE_ON_ZERO";
START TRANSACTION;
SET time_zone = "+00:00";


CREATE DATABASE IF NOT EXISTS `ailatrieuphu` DEFAULT CHARACTER SET utf8mb4 COLLATE utf8mb4_0900_ai_ci;
USE `ailatrieuphu`;

CREATE TABLE `account` (
  `id` int NOT NULL,
  `username` varchar(50) NOT NULL,
  `password` varchar(50) NOT NULL,
  `status` tinyint(1) NOT NULL
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_0900_ai_ci;

INSERT INTO `account` (`id`, `username`, `password`, `status`) VALUES
(1, 'test', 'test', 1),
(2, 'a', 'c', 1),
(3, 'b', 'b', 1);


CREATE TABLE `questions` (
  `id` int NOT NULL,
  `level` int NOT NULL,
  `question` varchar(500) CHARACTER SET utf8mb4 COLLATE utf8mb4_vi_0900_as_cs NOT NULL,
  `a` varchar(500) CHARACTER SET utf8mb4 COLLATE utf8mb4_vi_0900_as_cs NOT NULL,
  `b` varchar(500) CHARACTER SET utf8mb4 COLLATE utf8mb4_vi_0900_as_cs NOT NULL,
  `c` varchar(500) CHARACTER SET utf8mb4 COLLATE utf8mb4_vi_0900_as_cs NOT NULL,
  `d` varchar(500) CHARACTER SET utf8mb4 COLLATE utf8mb4_vi_0900_as_cs NOT NULL,
  `answer` int NOT NULL,
  `reward` int NOT NULL
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_0900_ai_ci;


INSERT INTO `questions` (`id`, `level`, `question`, `a`, `b`, `c`, `d`, `answer`, `reward`) VALUES
(1, 1, 'Điền tiếp vào câu tục ngữ sau: \"Chớp đông nhay nháy, gà gáy thì ....\"?', 'Toi', 'Mưa', 'Nắng', 'Râm', 2, 200),
(2, 1, 'Bài hát \"Da nâu\" do ca sĩ nào thể hiện?', 'Ngô Thanh Vân', 'Phi Thanh Vân', 'Nguyễn Thanh Vân', 'Đặng Thanh Vân', 2, 200),
(3, 1, 'Trong các thiết bị sau, thiết bị nào thường dùng để tạo ra gió?', 'Điện thoại', 'Máy tính', 'Quạt', 'Đồng hồ', 3, 200),
(4, 1, 'Danh từ nào sau đây là tên một loài chim?', 'Họa sĩ', 'Họa tiết', 'Họa mi', 'Họa bì', 3, 200),
(5, 1, 'Trong các nhãn hiệu sau, đâu không phải là nhãn hiệu sữa?', 'TH TrueMilk', 'Cô Gái Hà Lan', 'Vinamilk', 'Hòa Phát', 4, 200),
(6, 1, 'Đâu không phải là tên một môn thể thao?', 'Cầu Kiến', 'Cầu Mây', 'Cầu Lông', 'Khúc Côn Cầu', 1, 200),
(7, 1, 'Điền tiếp vào câu thành ngữ để chỉ vẻ đẹp: \"Chim sa cá ....\"?', 'Nổi', 'Nhảy', 'Lặn', 'Bơi', 3, 200),
(8, 1, 'Điền tiếp vào câu thành ngữ: \"Cơn đằng đông vừa trông vừa ...\"?', 'Sợ', 'Chạy', 'Trốn', 'Tắm', 2, 200),
(9, 1, 'Alibaba và bao nhiêu tên cướp?', '10', '20', '30', '40', 4, 200),
(10, 1, 'Điền tiếp vào câu thành ngữ: \"Con kiến mà kiện ...\"?', 'Con voi', 'Củ khoai', 'Đầu gối', 'Hộp đường', 2, 200),
(11, 1, 'Thứ nào sau đây không ăn được?', 'Bánh quy', 'Bánh Bao', 'Bánh xe', 'Bánh mật', 3, 200),
(12, 1, 'Điền tiếp vào câu tục ngữ: \"Ăn ... học hay\"?', 'Nói', 'Ngủ', 'No', 'Vóc', 4, 200),
(13, 1, 'Điền tiếp vào câu tục ngữ: \"Bán anh em xa mua ... gần\"?', 'Vợ', 'Cô gái', 'Láng giềng', 'Đồ cổ', 3, 200),
(14, 1, 'Câu tục ngữ: \"Bán phấn buôn hương\" để chỉ?', 'Người bán phấn', 'Người buôn hương', 'Người buôn bán hàng mã', 'Cô gái làng chơi', 4, 200),
(15, 1, 'Điền vào chỗ trống: \"Đi với bụt mặc áo cà sa, đi với ma mặc áo ...\"?', 'Áo dài', 'Áo giấy', 'Áo lụa', 'Áo gió', 2, 200),
(16, 1, 'Điền tiếp vào câu tục ngữ: \"Đi một ngày đàng, ...\"?', 'Gặp toàn hàng ngon', 'Mệt rũ chân tay', 'Học một sàng khôn', 'Vớ toàn điều xui', 3, 200),
(17, 1, 'Điền tiếp vào câu tục ngữ: \"Đói cho sạch, rách cho ...\"?', 'Thơm', 'Lành', 'Vuông', 'No', 1, 200),
(18, 1, 'Điền tiếp vào câu tục ngữ: \"Đời cha ăn mặn, đời con ...\"?', 'Ăn nhạt', 'Khát nước', 'Ăn cay', 'Chết đói', 2, 200),
(19, 1, 'Điền tiếp vào câu tục ngữ: \"Chết ... còn hơn sống nhục\"?', 'Trong', 'Xanh', 'Vinh', 'Sướng', 3, 200),
(20, 1, 'Điền tiếp vào câu thành ngữ: \"Kẻ cắp gặp ...\"?', 'Bà già', 'Công an', 'Thương binh', 'Nông dân', 1, 200),
(21, 2, 'Tác giả của bộ tranh truyện Nhật Bản lừng danh thế giới Doraemon?', 'Fujico Fujio', 'Takahashi Monona', 'Gosho Aoyama', 'Kajuki Takahashi', 1, 400),
(22, 2, 'Trong bàn cờ vua có bao nhiêu quân Tượng trắng?', '2', '4', '6', '8', 1, 400),
(23, 2, 'Trong các nhân vật sau đây, nhân vật nào tốt bụng nhất?', 'Chaien', 'Chaikô', 'Mèo máy', 'Nobita', 3, 400),
(24, 2, 'Ai là người tiêu diệt Xên Bọ Hung trong truyện 7 viên ngọc rồng?', 'Santa tóc xù', 'Sôngôhan', 'Cađíc', 'Sôngôku', 2, 400),
(25, 2, 'Loại xe nào sau đây phải chạy trên đường ray?', 'Xe lửa', 'Xe hơi', 'Xe tải', 'Xe môtô', 1, 400),
(26, 2, 'Mẹ ruột của mẹ chúng ta gọi là gì?', 'Bà sơ', 'Bà cố', 'Bà ngoại', 'Bà nội', 3, 400),
(27, 2, 'Điền vào chỗ trống: \"Thắng thì làm vua, thua thì làm ...\"?', 'Hoàng Thượng', 'Bụt', 'Cướp', 'Giặc', 4, 400),
(28, 2, 'Loại lực nào sau đây không có phản lực?', 'Lực hấp dẫn', 'Lực ma sát', 'Lực đàn hồi', 'Lực quán tính', 4, 400),
(29, 2, 'Thị xã Thái Bình trực thuộc tỉnh nào của nước ta?', 'Hưng Yên', 'Hà Nam', 'Nam Định', 'Thái Bình', 4, 400),
(30, 2, '\"Nghe là thấy\" là khẩu hiệu của mạng di động nào ở nước ta?', 'Sfone', 'Viettel', 'EVN', 'Mobiphone', 1, 400),
(31, 2, 'Đồng Tháp là một tỉnh thuộc miền nào của Việt Nam?', 'Đông Nam Bộ', 'Tây Nam Bộ', 'Tây Nguyên', 'Nam Trung Bộ', 2, 400),
(32, 2, 'Đảo Phú Quốc trực thuộc tỉnh nào?', 'Cà Mau', 'Kiên Giang', 'An Giang', 'Trà Vinh', 2, 400),
(33, 2, 'Tính chất nào phù hợp nhất với đề bài \"Có công mài sắt có ngày nên kim\"?', 'Phân tích', 'Ca ngợi', 'Tranh luận', 'Khuyên nhủ', 4, 400),
(34, 2, 'Có chí thì nên chúng ta đã học được ở môn học nào?', 'Hoá học', 'Văn học', 'Vật lý', 'Công nghệ', 2, 400),
(35, 2, 'Tập hợp số nào lớn nhất trong các tập sau?', 'Số tự nhiên', 'Số nguyên', 'Số hữu tỉ', 'Số thực', 4, 400),
(36, 2, 'Tác giả của bộ truyện tranh nổi tiếng Thám tử lừng danh Conan?', 'Fujico Fujio', 'Takahashi Monona', 'Gosho Aoyama', 'Kajuki Takahashi', 3, 400),
(37, 2, 'Trong bàn cờ vua có thể có nhiều nhất bao nhiêu quân Hậu?', '1', '7', '8', '9', 4, 400),
(38, 2, 'Trong các nhân vật sau đây, nhân vật nào thuộc bộ truyện tranh Đôrêmon?', 'Cađíc', 'Sôngôku', 'Chaien', 'Bumma', 3, 400),
(39, 2, 'Ai là người tiêu diệt Fide đại đế ở hành tinh Namếc trong truyện 7 viên ngọc rồng?', 'Sôngôhan', 'Cađíc', 'Sôngôku', 'Calíc', 3, 400),
(40, 2, 'Loại xe nào sau đây khác với các loại xe còn lại?', 'Xe lửa', 'Xe hơi', 'Xe đạp', 'Xe môtô', 1, 400),
(41, 2, 'Cha ruột của mẹ chúng ta gọi ta gì?', 'Ông nội', 'Ông sơ', 'Ông cố', 'Ông ngoại', 4, 400),
(42, 3, 'Trong các chương trình sau đây, chương trình nào dùng để duyệt Web?', 'Unikey', 'Internet explorer', 'Excel', 'Notepad', 2, 600),
(43, 3, 'Theo ngôn ngữ Tin học, trong hệ nhị phân thì 1 + 1 = ?', '1', '2', '10', '100', 3, 600),
(44, 3, 'Thành phần nào của máu tham gia vào quá trình đông máu ở vết thương?', 'Hồng cầu', 'Bạch cầu', 'Tiểu cầu', 'Hemoglobin', 3, 600),
(45, 3, 'Paris là thủ đô của quốc gia nào?', 'Anh', 'Pháp', 'Đức', 'Nga', 2, 600),
(46, 3, 'Washington DC là thủ đô nước nào?', 'Hoa Kỳ', 'Nhật Bản', 'Hàn Quốc', 'Tây Ban Nha', 1, 600),
(47, 3, 'Người ta thường xem môn thể thao nào là môn thể thao vua?', 'Bóng rổ', 'Điền kinh', 'Bóng đá', 'Bóng chuyền', 3, 600),
(48, 3, 'Hồ Chí Minh từng dạy: \"Lạc nước hai xe đành bỏ phí - Gặp thời một ... cũng thành công\"?', 'Pháo', 'Tướng', 'Tốt', 'Mã', 3, 600),
(49, 3, 'Phương pháp nào sau đây không phải là phương pháp chính làm chín thức ăn?', 'Luộc', 'Nấu', 'Hấp', 'Kho', 3, 600),
(50, 3, 'Nét đặc trưng của tự nhiên Lào?', 'Không có núi', 'Không có biển', 'Không có đồng bằng', 'Không có sông lớn', 2, 600),
(51, 3, 'Ở Việt Nam cứ 60 giây thì?', 'Một em bé ra đời', 'Một người tử vong', 'Nóng lên 0,01 độ', 'Một phút trôi qua', 4, 600),
(52, 3, 'Khi tham gia giao thông, đội mũ bảo hiểm là gì đối với chúng ta?', 'Cực hình', 'Nghĩa vụ', 'Trách nhiệm', 'Sở thích', 2, 600),
(53, 3, 'Tôn giáo có nhiều tín đồ nhất trên thế giới?', 'Phật giáo', 'Thiên chúa giáo', 'Hindu giáo', 'Hồi giáo', 2, 600),
(54, 3, 'Trong các chương trình sau đây, chương trình nào được dùng để duyệt Web?', 'Firefox', 'Opera', 'Paint', 'Firefox và Opera', 4, 600),
(55, 3, 'Một trong những kỳ quan của thế giới ở Ai Cập?', 'Kim Tự Tháp', 'Vườn treo Babylon', 'Vạn Lý Trường Thành', 'Đấu trường La Mã', 1, 600),
(56, 3, 'Trong Windows bấm tổ hợp phím nào để dán tập tin sau khi đã Copy?', 'Ctrl + C', 'Ctrl + V', 'Ctrl + X', 'Alt + V', 2, 600),
(57, 3, 'Cairo là thủ đô nước nào?', 'Ai Cập', 'Ả rập Saudi', 'Albania', 'Algeria', 1, 600),
(58, 3, 'Tác phẩm nào sau đây là của nhà văn nổi tiếng Ngô Thừa Ân?', 'Thuỷ Hử', 'Tam Quốc Diễn Nghĩa', 'Tây Du Ký', 'Hồng Lâu Mộng', 3, 600),
(59, 3, 'Nước nào sau đây có nhiều bò và trồng nhiều chè nhất thế giới?', 'Tây Ban Nha', 'Ấn Độ', 'Hoa Kỳ', 'Pháp', 2, 600),
(60, 3, 'Trái đất có bao nhiêu lục địa?', '3', '4', '5', '6', 3, 600),
(61, 3, 'Phương pháp nào không phải là phương pháp làm chín thực phẩm trong chất béo?', 'Rang', 'Rán', 'Xào', 'Đồ', 4, 600),
(62, 3, 'Phần mềm chuyên phá hoại hệ thống máy tính, gây phiền cho người sử dụng gọi là gì?', 'Hệ điều hành', 'Tập tin', 'Virus', 'Thư mục', 3, 600),
(63, 4, 'Từ nào trái nghĩa với từ thưa thớt?', 'Vắng vẻ', 'Vui vẻ', 'Đông đúc', 'Đầy đủ', 3, 1000),
(64, 4, 'Trong cờ Tướng, mỗi quân Tốt có thể đi được bao nhiêu vị trí?', '44', '45', '46', '47', 4, 1000),
(65, 4, 'Xét về sức nặng chịu được, con vật nào sau đây khoẻ nhất?', 'Voi', 'Kiến', 'Hà mã', 'Trâu', 2, 1000),
(66, 4, 'Trong các con vật sau đây, con nào gần gũi với con người nhất?', 'Thỏ', 'Chó', 'Lợn', 'Rùa', 2, 1000),
(67, 4, 'Trong các loài dưới đây, con nào không thuộc loài bò sát?', 'Khủng long', 'Rắn', 'Cá sấu', 'Ốc bươu', 4, 1000),
(68, 4, 'Refresh lại máy tính, ta có thể sử dụng phím tắt gì?', 'CtrlR', 'F5', 'AtlR', 'F8', 2, 1000),
(69, 4, 'Để có ánh sáng màu hồng nhạt, phải trộn hai màu nào với nhau?', 'Đỏ với lục', 'Đỏ với lam', 'Đỏ với tím', 'Đỏ với vàng', 2, 1000),
(70, 4, 'Quốc gia nào sau đây có tên trùng với tên thủ đô?', 'Malaysia', 'Singapore', 'Indonesia', 'Brunei', 2, 1000),
(71, 4, 'Trong các phần mềm sau đây, phần mềm nào dùng để nén dữ liệu?', 'Winzip', 'Unikey', 'Kingsoft Office', 'Autocad', 1, 1000),
(72, 4, 'Câu \"Một quốc gia sung sướng là một quốc gia không cần đến những vị anh hùng\" thuộc thể loại văn học?', 'Ca dao', 'Tục ngữ', 'Danh ngôn', 'Châm ngôn', 3, 1000),
(73, 4, '\"Người biết đức tất không thích tiếng tăm lừng lẫy\" thuộc thể loại văn học nào?', 'Danh ngôn', 'Châm ngôn', 'Ca dao', 'Tục ngữ', 2, 1000),
(74, 4, '\"Nhỏ thì nhờ mẹ nhờ cha. Lớn lên nhờ vợ, về già nhờ con\" thuộc thể loại văn học nào?', 'Tục ngữ', 'Ca dao', 'Thành ngữ', 'Danh ngôn', 2, 1000),
(75, 4, '\"Nụ cười châu chấu đá xe. Tưởng rằng chấu ngã ai dè xe nghiêng\" thuộc thể loại văn học nào?', 'Danh ngôn', 'Thành ngữ', 'Tục ngữ', 'Ca dao', 4, 1000),
(76, 4, '\"Ru con con ngủ cho rồi. Mẹ ra chỗ vắng mẹ ngồi than thân\" thuộc thể loại văn học nào?', 'Tục ngữ', 'Ca dao', 'Thành ngữ', 'Danh ngôn', 2, 1000),
(77, 4, 'Hầu như diện tích bề mặt của châu Nam cực toàn là?', 'Tuyết', 'Băng', 'Núi', 'Thung lũng', 2, 1000),
(78, 4, 'Câu văn: \"đêm đã về khuya\" thuộc kiểu câu nào?', 'Câu đơn', 'Câu rút gọn', 'Câu đặc biệt', 'Câu bị động', 1, 1000),
(79, 4, 'Trong cờ Tướng, mỗi quân Tượng có thể đi được bao nhiêu vị trí?', '6', '7', '8', '9', 2, 1000),
(80, 4, 'Loài động vật lớn nhất trên thế giới?', 'Khủng long', 'Cá voi', 'Quái vật hồ Loch Ness', 'Voi', 2, 1000),
(81, 4, 'Trong các con vật sau đây, con nào có nhiều chân nhất?', 'Giun', 'Rết', 'Bọ cạp', 'Bướm', 2, 1000),
(82, 4, 'Trong các loài dưới đây, loài nào đã bị tuyệt chủng?', 'Đại bàng', 'Rắn hổ mang', 'Lạc đà', 'Khủng long', 4, 1000),
(83, 4, 'Trong mặt phẳng, hai đường thẳng cắt nhau chia mặt phẳng làm mấy phần?', '2', '3', '4', '5', 3, 1000),
(84, 5, 'Trong các số sau đây, số nào chia hết cho 9?', '7720', '7721', '8821', '8822', 3, 2000),
(85, 5, 'Trong các từ sau đây, từ nào không dùng để chỉ tóc?', 'Hoa râm', 'Uốn phồng', 'Râm bụt', 'Ép cụp', 3, 2000),
(86, 5, 'Khi tán gẫu bằng Yahoo Messenger, người ta thường sử dụng thiết bị nào để chia sẻ hình ảnh trực tiếp?', 'Microphone', 'Webcame', 'Headphone', 'Modemn', 2, 2000),
(87, 5, 'Nam tài tử Robert Pattinson tham gia vào loạt phim nổi tiếng nào?', 'Iron man', 'X-man', 'The Twilight Saga', 'Fast and Furious', 3, 2000),
(88, 5, 'Tờ giấy bạc 5000 đồng có in hình gì?', 'Vịnh Hạ Long', 'Khai thác dầu khí', 'Hồ Chí Minh', 'Quốc huy', 3, 2000),
(89, 5, '\"Năm anh em trên một chiếc xe tăng\" là sáng tác của nhạc sĩ nào?', 'Doãn Nho', 'Huy Du', 'Triều Dâng', 'Phạm Tuyên', 1, 2000),
(90, 5, 'Kilimanjaro là ngọn núi cao nhất châu lục nào?', 'Châu Á', 'Châu Phi', 'Châu Âu', 'Châu Mỹ', 2, 2000),
(91, 5, 'Dec trong tiếng Anh là tháng mấy trong năm?', 'Tháng 1', 'Tháng 4', 'Tháng 8', 'Tháng 12', 4, 2000),
(92, 5, 'March trong tiếng Anh là tháng mấy trong năm?', 'Tháng 12', 'Tháng 6', 'Tháng 3', 'Tháng 5', 3, 2000),
(93, 5, 'Trang tìm kiếm thông tin mạnh nhất trên Internet là trang nào tính đến năm 2010?', 'Yahoo', 'Google', 'Live', 'Search', 2, 2000),
(94, 5, '.mp3 là phần mở rộng của loại file nào?', 'File văn bản', 'File hình ảnh', 'File âm nhạc', 'File video', 3, 2000),
(95, 5, 'Quần đảo Hoàng Sa nằm ở phía nào của quần đảo Trường Sa?', 'Tây', 'Đông', 'Nam', 'Bắc', 4, 2000),
(96, 5, 'Từ nào sau đây không phải là từ láy?', 'Da diết', 'Dập dìu', 'Thưa thớt', 'Phố phường', 4, 2000),
(97, 5, 'Trên bàn cờ Tướng, có tổng cộng bao nhiêu điểm mà các quân có thể đến?', '80', '90', '100', '120', 2, 2000),
(98, 5, 'Muỗi thường đốt là muỗi đực hay muỗi cái?', 'Muỗi cái', 'Muỗi đực', 'Muỗi cái và muỗi đực', 'Cả 2 không đốt', 1, 2000),
(99, 5, 'Trong các con vật sau đây, con nào khác với các con vật còn lại?', 'Vịt', 'Ngỗng', 'Gà', 'Ngan', 3, 2000),
(100, 5, 'Con sông chảy qua thành phố Huế là sông gì?', 'Sông Tô Lịch', 'Sông Đồng Nai', 'Sông Mê Kông', 'Sông Hương', 4, 2000),
(101, 5, 'Phần mềm nào là từ điển trong tin học?', 'Unikey', 'Opera', 'LacViet', 'Teracopy', 3, 2000),
(102, 5, 'Dụng cụ nào sau đây biến đổi cơ năng thành điện năng?', 'Máy bơm nước', 'Đinamô', 'Máy hơi nước', 'Động cơ điện', 2, 2000),
(103, 5, 'Mặt trước của tờ giấy bạc 10.000 đồng bằng cotton có in hình gì?', 'Hồ Chí Minh', 'Khai thác dầu khí', 'Vịnh Hạ Long', 'Cảng Hải Phòng', 1, 2000),
(104, 5, 'Loại cây nào không thuộc nhóm cây thực phẩm?', 'Nấm hương', 'Măng', 'Quế', 'Mộc nhĩ', 3, 2000),
(105, 6, 'Đơn vị đo lực là gì?', 'Kg', 'N', 'm', 'Nm3', 2, 3000),
(106, 6, 'Từ "nó" trong câu: "Nó dài dài, màu nâu, hay nheo lại như chổi nắng" là loại từ gì?', 'Quan hệ từ', 'Đại từ', 'Tình thái từ', 'Chỉ từ', 4, 3000),
(107, 6, 'Lúc Bác Hồ ở Hồng Kông, Bác lấy tên là gì?', 'Hồ Chí Minh', 'Nguyễn Tất Thành', 'Tống Văn Sơ', 'Nguyễn Ái Quốc', 3, 3000),
(108, 6, 'Panama là thủ đô của quốc gia nào?', 'Pakistan', 'Palau', 'Panama', 'Papua New Guinea', 3, 3000),
(109, 6, 'Quốc gia nào sau đây không thuộc Châu Phi?', 'Angola', 'Hy Lạp', 'Liberia', 'Somalia', 2, 3000),
(110, 6, 'Sea Games 22 được tổ chức ở Việt Nam có bao nhiêu môn thi đấu?', '28 môn', '32 môn', '34 môn', '38 môn', 2, 3000),
(111, 6, 'Bản trường ca "Đẻ đất đẻ nước" là của dân tộc nào?', 'Hmông', 'Êđê', 'Chăm', 'Mường', 4, 3000),
(112, 6, 'Thị xã Uông Bí thuộc tỉnh nào của nước ta?', 'Hải Phòng', 'Hải Dương', 'Quảng Ninh', 'Bắc Giang', 3, 3000),
(113, 6, 'Thị xã Hồng Lĩnh trực thuộc tỉnh nào của nước ta?', 'Nghệ An', 'Hà Tây', 'Hà Tĩnh', 'Ninh Bình', 3, 3000),
(114, 6, 'Sóng dừng là một trường hợp của hiện tượng gì?', 'Cộng hưởng', 'Triệt tiêu', 'Giao thoa sóng', 'Tăng dần', 3, 3000),
(115, 6, '"Một cõi đi về" là sáng tác của nhạc sĩ nào?', 'Văn Cao', 'Phan Huỳnh Điểu', 'Trịnh Công Sơn', 'Hoàng Hiệp', 3, 3000),
(116, 6, 'Tỉnh nào nằm ở ngã ba biên giới Lào, Campuchia và Việt Nam?', 'Kon Tum', 'Đắc Lắc', 'Đắc Nông', 'Gia Lai', 1, 3000),
(117, 6, 'Càng lên cao, áp suất khí quyển sẽ như thế nào?', 'Càng tăng', 'Càng giảm', 'Không thay đổi', 'Tăng dần rồi giảm', 2, 3000),
(118, 6, 'Sóng điện từ là sóng gì?', 'Dừng', 'Dọc', 'Ngang', 'Vừa ngang vừa dọc', 3, 3000),
(119, 6, 'Động đất có độ Richter trong khoảng nào thì phá huỷ hầu hết các công trình xây dựng thông thường, nứt đất?', 'Lớn hơn 10', '9-10', '7-8', '4-5', 3, 3000),
(120, 6, 'Ngọn núi nào cao nhất thế giới?', 'Makalu', 'Lhoste', 'Kanchenjunga', 'Everest', 4, 3000),
(121, 6, 'Tác phẩm "Chí Phèo" của Nam Cao được đổi tên mấy lần?', '2', '3', '4', '5', 2, 3000),
(122, 6, 'Nhà thơ Nguyễn Đình Chiểu bị dị tật gì?', 'Điếc', 'Thần Kinh', 'Mù', 'Câm', 3, 3000),
(123, 6, 'Quang Dũng tác giả bài thơ Tây Tiến tên thật là gì?', 'Bùi Đình Diệm', 'Nguyễn Quang Dũng', 'Trần Nhật Tân', 'Ngô Thì Nhậm', 1, 3000),
(124, 6, 'Lễ hội Canaval là lễ hội nổi tiếng ở quốc gia nào?', 'Mexico', 'Brazil', 'Argentina', 'Chile', 2, 3000),
(125, 6, 'Đơn vị khối lượng riêng là gì?', 'N/m', 'N/m3', 'Kg/m2', 'Kg/m3', 4, 3000),
(126, 6, 'Từ nào dưới đây là từ tượng thanh?', 'Kiêu hãnh', 'Xa xăm', 'Khe khẽ', 'Lộn xộn', 3, 3000),
(127, 7, 'Ngày thu phân là ngày nào?', '22-06', '22-04', '22-03', '23-09', 4, 6000),
(128, 7, 'Tim loài ếch có mấy ngăn?', '2 ngăn', '3 ngăn', '3 ngăn có vách hụt', '4 ngăn', 2, 6000),
(129, 7, 'Nền kinh tế lớn thứ 3 Thế giới tính theo GDP?', 'Ấn Độ', 'Nhật Bản', 'Đức', 'Việt Nam', 3, 6000),
(130, 7, 'Quần đảo lớn nhất thế giới nằm ở đâu?', 'Châu Đại Dương', 'Châu Nam Cực', 'Bắc Mỹ', 'Đông Nam Á', 4, 6000),
(131, 7, 'Dany Boyle là đạo diễn của bộ phim nào?', 'Triệu phú khu ổ chuột', 'Ở nhà một mình', 'Harry Potter', 'Transformer', 1, 6000),
(132, 7, 'Hy Lạp nằm trên bán đảo nào của châu Âu?', 'Xcangdinavi', 'Butrida', 'Balkan', 'Queensland', 3, 6000),
(133, 7, 'Ứng dụng của ròng rọc trong đời sống và trong kĩ thuật là?', 'Cần cẩu', 'Cái mở nút chai', 'Kìm nhổ đinh', 'Đòn bẩy', 1, 6000),
(134, 7, 'Loại thực phẩm nhiều gluxit nhất là?', 'Đậu tương và đậu xanh', 'Gạo và lúa mì', 'Giá đỗ và trứng', 'Dầu lạc và vừng', 2, 6000),
(135, 7, 'Chu vi của thân cây Bao báp ở châu Phi có thể khoảng bao nhiêu?', '10-30 m', '20-40 m', '30-40 m', '30-50 m', 1, 6000),
(136, 7, 'Sông Đà và sông Lưu là 2 phụ lưu của sông nào?', 'Sông Hồng', 'Sông Thao', 'Sông Tràng Tiền', 'Sông Thu Bồn', 1, 6000),
(137, 7, 'Yaounde là thủ đô của quốc gia nào?', 'Canada', 'Cambodia', 'Cameroon', 'Chile', 3, 6000),
(138, 7, 'Monacco là thủ đô nước nào?', 'Monaco', 'Ma Rốc', 'Mozambique', 'Mexico', 1, 6000),
(139, 7, 'Doha là thủ đô nước nào?', 'Qutar', 'Oman', 'Yemen', 'Samoa', 1, 6000),
(140, 7, 'Stockholm là thủ đô nước nào?', 'Na Uy', 'Thuỵ Điển', 'Phần Lan', 'Hà Lan', 2, 6000),
(141, 7, 'Lusaka là thủ đô nước nào?', 'Zambia', 'Gambia', 'Zimbabue', 'Tanzania', 1, 6000),
(142, 7, 'Ai là nhà triết học có ảnh hưởng lớn nhất trong lịch sử Trung Quốc?', 'Lão Tử', 'Khổng Tử', 'Mạnh Tử', 'Trạng Tử', 2, 6000),
(143, 7, 'Xe máy do người nước nào phát minh?', 'Anh', 'Đức', 'Pháp', 'Mỹ', 2, 6000),
(144, 7, 'Mùa xuân nho nhỏ là sáng tác của nhạc sĩ nào?', 'Trần Hoàn', 'Xuân Hồng', 'Trịnh Công Sơn', 'Đỗ Nhuận', 1, 6000),
(145, 7, 'Quốc kỳ của quốc gia nào chỉ có một màu xanh lá cây?', 'Marroc', 'Sudan', 'Lybia', 'Algieria', 3, 6000),
(146, 7, 'World Cup đầu tiên có bao nhiêu đội tuyển quốc gia tham dự?', '13', '14', '15', '16', 1, 6000),
(147, 7, 'Trong truyện Ông lão đánh cá và con cá vàng, ông lão đã ra bờ sông mấy lần?', '3', '4', '5', '6', 4, 6000),
(148, 8, 'Ai là tác giả của "Đại Việt Sử Ký toàn thư"?', 'Lê Văn Hưu', 'Nguyễn Trãi', 'Ngô Thì Nhậm', 'Ngô Sỹ Liên', 4, 10000),
(149, 8, 'Để tắt một cửa sổ trong Hệ điều hành Windows, có thể dùng tổ hợp phím nào?', 'Ctrl + F4', 'Alt + F4', 'Shift + F4', 'Ctrl + Shift + F4', 2, 10000),
(150, 8, 'Chức quan mang lại quyền tự chủ cho nước ta cuối thời chịu ách đô hộ của quân Nam Hán?', 'Thứ sử', 'Thái Thú', 'Tiết Độ Sứ', 'Hào trưởng', 3, 10000),
(151, 8, 'CONCACAF là viết tắt của tổ chức nào?', 'Liên minh quân sự Caribe', 'LĐBĐ Bắc Trung Mỹ và Caribe', 'LĐ Bóng Đá Nam Mỹ và Caribe', 'Liên Minh quân sự Nam Mỹ và Caribe', 2, 10000),
(152, 8, 'Đèo Đê Bay, Sông Cu Đê là những địa danh thuộc tỉnh thành phố nào sau đây?', 'Quảng Nam', 'Hậu Giang', 'Đà Nẵng', 'Cần Thơ', 3, 10000),
(153, 8, 'Ban đầu x=1, y=2. Sau khi sử dụng temp=x, x=y, y=temp. Vậy x=? y=?', 'x=1, y=2', 'x=1, y=1', 'x=2, y=2', 'x=2, y=1', 4, 10000),
(154, 8, 'Bệnh AIDS được phát hiện đầu tiên vào năm nào?', '1981', '1983', '1985', '1987', 1, 10000),
(155, 8, 'Nguyên tố Canxi thuộc chu kì nào?', 'Chu kì 2', 'Chu kì 3', 'Chu kì 4', 'Chu kì 5', 3, 10000),
(156, 8, 'Trụ sở của nghị viện Châu Âu nằm ở đâu?', 'Strasbourg', 'Genève', 'London', 'Paris', 1, 10000),
(157, 8, 'Dãy núi ngăn cách châu Âu và châu Á?', 'Phanxiphang', 'Olympia', 'Everest', 'Uran', 4, 10000),
(158, 8, 'Trên tiền của New Zealand có hình con gì?', 'Chim Ruồi', 'Đại Bàng', 'Kiwi', 'Bói Cá', 3, 10000),
(159, 8, 'Hành tinh nào có nhiệt độ trung bình cao nhất trong hệ mặt trời?', 'Sao Thuỷ', 'Sao Kim', 'Sao Thiên Vương', 'Sao Diêm Vương', 2, 10000),
(160, 8, 'Hai nốt Mi -Đô , trong đó Mi là âm dưới, Đô là âm trên tạo thành quãng mấy?', 'Quãng 4', 'Quãng 5', 'Quãng 6', 'Quãng 7', 3, 10000),
(161, 8, 'Tổ chức y tế thế giới gọi tắt là gì?', 'WHO', 'UNESCO', 'UNICEF', 'NATO', 1, 10000),
(162, 8, 'Hiện tượng mưa Axit do khí nào tạo nên?', 'SO2', 'SO3', 'O2', 'NO3', 1, 10000),
(163, 8, 'Bãi tắm Thiên Cầm thuộc tỉnh nào?', 'Hà Nam', 'Hải Phòng', 'Ninh Thuận', 'Hà Tĩnh', 4, 10000),
(164, 8, 'Prague là thủ đô nước nào?', 'CH Séc', 'SH Tchad', 'Sh Sip', 'Colombia', 1, 10000),
(165, 8, 'Vận tốc ánh sáng truyền trong môi trường chân không là bao nhiêu?', '3.000kms', '30.000kms', '300.000kms', '3.000.000kms', 3, 10000),
(166, 8, 'Cờ vua được ra đời ở quốc gia nào?', 'Trung Quốc', 'Ấn Độ', 'Việt Nam', 'Nhật Bản', 2, 10000),
(167, 8, 'Bóng đá du nhập vào Việt Nam từ năm nào?', '1896', '1850', '1905', '1825', 1, 10000),
(168, 8, 'Điểm cuối của cầu Cần Thơ thuộc địa phận quận, huyện nào của Cần Thơ?', 'Ninh Kiều', 'Cái Răng', 'Trà Ôn', 'Châu Thành', 2, 10000),
(169, 9, 'Câu nói:"Nếu bệ hạ muốn hàng giặc trước hãy chém đầu thần rồi hãy hàng" là câu nói của ai?', 'Trần Thủ Độ', 'Trần Quốc Tuấn', 'Trần Quốc Toản', 'Trần Nguyên Hãn', 2, 14000),
(170, 9, 'Ngành nào trong các ngành sau đây không phải là ngành dịch vụ chủ yếu?', 'Xuất nhập khẩu', 'Bưu chính viễn thông', 'Vận tải thuỷ', 'Du lịch sinh thái', 2, 14000),
(171, 9, 'Hamplet là Hoàng tử của Vương quốc nào?', 'Hà Lan', 'Anh', 'Đan Mạch', 'Thuỵ Điển', 3, 14000),
(172, 9, 'Suva là thủ đô nước nào?', 'Fiji', 'Phần Lan', 'Pháp', 'El Salvador', 1, 14000),
(173, 9, 'Tim bạn đập trung bình bao nhiêu lần một ngày?', '50.000', '100.000', '150.000', '200', 2, 14000),
(174, 9, 'Ở nước nào mà người ta ăn 12 quả nho vào lúc đồng hồ báo hiệu thời khắc giao thừa, mỗi quả cho một nhịp chuông của đồng hồ?', 'Úc', 'Pháp', 'Tây Ban Nha', 'Canada', 3, 14000),
(175, 9, 'Chùa Vàng nằm ở quốc gia nào?', 'Thái Lan', 'Ấn Độ', 'Trung Quốc', 'Myanmar', 4, 14000),
(176, 9, 'Diện tích đất đai ở Việt Nam được xếp hạng bao nhiêu trên thế giới?', '65', '85', '55', '75', 1, 14000),
(177, 9, 'Vòng chung kết cúp bóng đá châu Phi lần thứ 20 diễn ra vào năm nào?', '1988', '1990', '1992', '1996', 4, 14000),
(178, 9, 'Chủ nhà vòng chung kết cúp bóng đá châu Phi lần thứ 22 là quốc gia nào?', 'Ghana và Nigieria', 'Ai Cập', 'Nam Phi', 'Bờ Biển Ngà', 1, 14000),
(179, 9, 'SEA Games lần thứ 20 năm 1999, quốc gia nào đăng cai?', 'Indonesia', 'Lào', 'Việt Nam', 'Brunei', 4, 14000),
(180, 9, 'Kim loại nào sau đây không bao giờ được tìm thấy ở dạng tự do trong thiên nhiên?', 'Vàng', 'Bạch kim', 'Bạc', 'Nhôm', 4, 14000),
(181, 9, 'Liên đoàn bóng bàn thế giới gọi tắt là gì?', 'FIFA', 'FIVB', 'ITTF', 'FIDE', 3, 14000),
(182, 9, 'Thành phố nào đăng cai Á vận hội ASIAD năm 1951?', 'Manila Philippines', 'Tokyo Nhật Bản', 'New Dehli Ấn Độ', 'Hiroshima Nhật Bản', 3, 14000),
(183, 9, 'Câu lạc bộ nào vô địch cúp C1 châu Âu UEFA Champions League năm 1990?', 'Sao đỏ Belgrade', 'Manchester United', 'Valencia FC', 'AC Milan', 4, 14000),
(184, 9, 'Câu lạc bộ nào vô địch cúp C1 châu Âu UEFA Champions League năm 1970?', 'AC Milan', 'Feyenood Rotterdam', 'Bayern Munich', 'Real Madrid', 2, 14000),
(185, 9, 'Cầu thủ nào là vua phá lưới V League mùa bóng năm 2007?', 'Gaston Merlo', 'Lazaro de Souza', 'Kesley Alves', 'Almeida', 4, 14000),
(186, 9, 'Trong văn chương cổ điển, người xưa coi lá cây nào báo hiệu mua thu đến?', 'Lá cây gạo', 'Lá ngô đồng', 'Lá cây đa', 'Lá mít', 2, 14000),
(187, 9, 'Hành tinh nào sau đây lớn thứ 3 trong hệ mặt trời?', 'Sao Thổ', 'Sao Thiên Vương', 'Sao Hải Vương', 'Trái đất', 2, 14000),
(188, 9, 'Các công trình kiến trúc nổi tiếng ở Huế còn lại đến ngày nay đã được xây dựng dưới thời?', 'Nhà Lê', 'Trịnh Nguyên phân tranh', 'Nhà Nguyễn', 'Tây Sơn', 3, 14000),
(189, 9, 'Huyện đảo Trường Sa thuộc tỉnh thành phố nào của Việt Nam?', 'Thừa Thiên Huế', 'Khánh Hoà', 'Quảng Nam', 'Quảng Ngãi', 2, 14000),
(190, 10, 'Trong bức tranh nổi tiếng Bữa tiệc ly vẽ chúa Jesus và 12 học trò, Leonardo de Vinci đã sử dụng chất liệu nào?', 'Sơn dầu trên toan', 'Sơn dầu trên gỗ', 'Sơn dầu và Tempera trên tường', 'Tempera trên toan', 3, 22000),
(191, 10, '"Đêm đông" là sáng tác của nhạc sĩ nào?', 'Phạm Tuyên', 'Đỗ Nhuận', 'Phan Huỳnh Điểu', 'Nguyễn Văn Thương', 4, 22000),
(192, 10, 'Bài thơ nào sau đây không nằm trong tập Nhật ký trong tù của Hồ Chí Minh?', 'Tân xuất ngục học đăng sơn', 'Tảo giải', 'Thế lộ nan', 'Tẩu lộ', 1, 22000),
(193, 10, 'Trung bình khi xuống thấp 100m, thì nhiệt độ tăng 1 độ C là ở tầng khí quyển nào?', 'Tầng giữa', 'Tầng đối lưu', 'Tầng bình lưu', 'Tầng nhiệt', 2, 22000),
(194, 10, 'Bao nhiêu phần trăm dân số Trung Quốc tham gia xây dựng Vạn Lý Trường Thành?', '50', '60', '70', '80', 3, 22000),
(195, 10, 'Người Việt Nam đầu tiên tạo ra giống lúa Nông nghiệp 1?', 'Lương Đình Của', 'Trần Tiến Phát', 'Nguyễn Nông Thôn', 'Bùi Tấn Thạch', 1, 22000),
(196, 10, 'Hòn đảo nào là nguyên nhân gây ra cuộc chiến tranh giữa Anh và Argentina năm 1982?', 'Vlieland', 'Ameland', 'Falklands', 'Texel', 3, 22000),
(197, 10, 'Loại đất chiếm diện tích lớn nhất nước ta là loại đất nào?', 'Đất phù sa', 'Đất mùn núi trung bình', 'Đất mùn núi cao', 'Đất Feralit đồi núi thấp', 4, 22000),
(198, 10, 'Phần lớn cư dân ở đảo Madagasca là người của quốc gia nào?', 'Nam Phi', 'Madagasca', 'Indonesia', 'Ấn Độ', 3, 22000),
(199, 10, 'Thimphu là thủ đô của quốc gia nào?', 'Belarus', 'Banglades', 'Bhutan', 'Bolivia', 3, 22000),
(200, 10, 'Nước nào khởi đầu cuộc cách mạng khoa học kĩ thuật lần thứ 2?', 'Anh', 'Nhật', 'Mỹ', 'Liên Xô', 3, 22000),
(201, 10, 'Ai được coi là ông tổ ngành Dược Việt Nam?', 'Hoa Đà', 'Hải Thượng Lãn Ông', 'Tuệ Tĩnh', 'Phạm Ngọc Thạch', 3, 22000),
(202, 10, 'Nước nào phóng thành công tàu vũ trụ có người lái lên trạm không gian lần thứ 3?', 'Nhật Bản', 'Singapore', 'Hàn Quốc', 'Trung Quốc', 4, 22000),
(203, 10, 'Trận chiến đầu tiên mà Napoleon chỉ huy là trận nào?', 'Trận Magenrô', 'Trận chiến thành Tulông', 'OaHeLê', 'Trận Auxteclit', 2, 22000),
(204, 10, '"Những bông hoa trong vườn Bác" là sáng tác của nhạc sĩ nào?', 'Phan Huỳnh Điểu', 'Trần Kiết Tường', 'Văn Dung', 'Huỳnh Thơ', 3, 22000),
(205, 10, 'Bài thơ nào là bài thơ đầu tiên trong tập Nhật ký trong tù của Hồ Chí Minh?', 'Buổi sớm', 'Mở đầu tập nhật ký', 'Cơm tù', 'Giả gạo', 2, 22000),
(206, 10, 'Tầng nào của khí quyển chiếm lượng hơi nước?', 'Tầng bình lưu', 'Tầng đối lưu', 'Tầng giữa', 'Tầng ngoài', 2, 22000),
(207, 10, 'Hồ nước nào lớn nhất Đông Nam Á?', 'Hồ Victoria', 'Hồ Ladoga', 'Hồ Lhagba Pool', 'Hồ Tonlesap', 4, 22000),
(208, 10, 'Theo các nước phương Tây, chủ nhật tuần thứ 2 tháng 4 là ngày lễ gì?', 'Lễ Haloween', 'Lễ phục sinh', 'Lễ Valentine', 'Lễ tạ ơn', 2, 22000),
(209, 10, 'Nhiệt độ trung bình năm của không khí nước ta trên ?', '20 độ C', '22 độ C', '23 độ C', '24 độ C', 1, 22000),
(210, 10, 'Ngân hàng đầu tiên ra đời trên thế giới ở quốc gia nào?', 'Đức', 'Pháp', 'Anh', 'Hoa Kì', 4, 22000),
(211, 11, 'Đậu tương, lạc, thuốc lá được trồng nhiều nhất trên loại đất nào?', 'Đất nhiễm mặn', 'Đất phù sa', 'Đất bạc màu', 'Đất xám', 3, 30000),
(212, 11, 'Thời Tiền Lê trong lịch sử Việt Nam do ai lập nên?', 'Lê Lợi', 'Lê Thái Tổ', 'Lê Hoàn', 'Lê Thánh Tông', 3, 30000),
(213, 11, 'Đường xích đạo chạy qua bao nhiêu quốc gia?', '12', '13', '14', '15', 1, 30000),
(214, 11, 'Ở vòng cực Bắc, ngày duy nhất dài 24h là?', '21/03', '22/06', '23/09', '22/12', 2, 30000),
(215, 11, 'Việt Nam trở thành thành viên của Liên Hợp Quốc vào năm nào?', '1974', '1975', '1976', '1977', 3, 30000),
(216, 11, 'Hiệp ước nào chấm dứt chiến tranh thế giới thứ hai?', 'Warsaw', 'Versailles', 'Paris', 'Geneve', 2, 30000),
(217, 11, 'Quốc gia nào đã tổ chức Thế vận hội mùa hè Olympic năm 1964?', 'Mexico', 'Canada', 'Liên Xô', 'Nhật Bản', 4, 30000),
(218, 11, 'Mandalay là cố đô của đất nước Châu Á nào?', 'Sri Lanka', 'Butan', 'Myanmar', 'Nepal', 3, 30000),
(219, 11, 'Sông nào không phải của khu vực Đông Á?', 'Amua', 'Ơ phrat', 'Hoàng Hà', 'Trường Giang', 2, 30000),
(220, 11, 'Quốc kỳ Indonesia có 2 màu tượng trưng cho điều gì?', 'Gạo, hoa', 'Gạo, muối', 'Gạo, đường', 'Đường, hoa', 3, 30000),
(221, 11, 'Sofia là thủ đô của quốc gia nào?', 'Brunei', 'Bangladesh', 'Bulgaria', 'Hungaria', 3, 30000),
(222, 11, 'Hồ nước nào có đường xích đạo chạy qua?', 'Hồ Victoria', 'Hồ Ladoga', 'Hồ Baikal', 'Hồ Tonglesap', 1, 30000),
(223, 11, 'Trong cuộc khai thác thuộc địa lần 2, thực dân Pháp đầu tư vốn nhiều nhất vào ngành nào?', 'Công nghiệp chế biến', 'Nông nghiệp và khai thác', 'Nông nghiệp và thương mại', 'Giao thông vận tải', 2, 30000),
(224, 11, 'Máy vi tính vào giai đoạn đầu được dùng cho?', 'Quân sự', 'Điện toán', 'Kinh tế', 'Khoa học', 1, 30000),
(225, 11, 'Trên trái đất, nơi mỗi năm chỉ có 1 ngày dài 24h là?', 'Xích đạo', 'Vòng cực', 'Cực', 'Chí tuyến', 2, 30000),
(226, 11, 'Thủ đô nào lâu đời nhất Đông Nam Á?', 'Hà Nội', 'Băng Cốc', 'Phnom Penh', 'Viên Chăn', 1, 30000),
(227, 11, 'Đàn Talư là của dân tộc nào ở nước ta?', 'Thái', 'Raglai', 'Vân Kiều', 'HMông', 3, 30000),
(228, 11, 'Sản lượng điện bình quân theo đầu người cao nhất thế giới thuộc về?', 'Nhật Bản', 'Nga', 'Hoa Kỳ', 'Trung Quốc', 3, 30000),
(229, 11, 'Người châu Âu đầu tiên thám hiểm sông Mekong là người quốc gia nào?', 'Pháp', 'Bồ Đào Nha', 'Hà Lan', 'Tây Ban Nha', 2, 30000),
(230, 11, 'Đến năm 2002 tổ chức ASEAN gồm bao nhiêu quốc gia?', '10', '9', '8', '7', 1, 30000),
(231, 11, 'Chiến thắng Giồng Thị Đam , Gò Quảng Cung là mở màn của cuộc khởi nghĩa nào?', 'Khởi nghĩa Nam Kỳ', 'Khởi nghĩa Lam Sơn', 'Đồng khởi Bến Tre', 'Khởi nghĩa Hai Bà Trưng', 3, 30000),
(232, 12, 'Trung tâm chế tạo pháo hoa của châu Âu vào khoảng thế kỷ XV là ở đâu?', 'Florencia Italia', 'Berlin Đức', 'Paris Pháp', 'London Anh', 1, 40000),
(233, 12, 'Máy tính xách tay laptop được phát minh vào năm nào?', '1975', '1981', '1990', '1995', 2, 40000),
(234, 12, 'Bạn cho biết bức hoạ Bữa ăn tối cuối cùng là của danh hoạ nào?', 'Pablo Picasso', 'Leonardo da Vinci', 'Vincent VanGogh', 'Walt Disney', 2, 40000),
(235, 12, 'Ở châu Âu, nước nào là nước xây dựng vườn cấm quốc gia đầu tiên năm 1969?', 'Ba Lan', 'Thuỵ Điển', 'Đan Mạch', 'Úc', 2, 40000),
(236, 12, 'Huyện Chí Linh trực thuộc tỉnh nào của nước ta?', 'Hải Phòng', 'Hải Dương', 'Thái Bình', 'Hưng Yên', 2, 40000),
(237, 12, 'Khi ở một mình trên đảo hoang, động vật nào được Robinson sử dụng nhiều nhất?', 'Lợn rừng', 'Bò sữa', 'Dê', 'Cừu', 3, 40000),
(238, 12, 'Quốc gia nào đã tổ chức Thế vận hội mùa đông năm 1980?', 'Hoa Kỳ', 'Na Uy', 'Pháp', 'Nga', 1, 40000),
(239, 12, 'Điểm đặc trưng nhất của các sinh vật trong giới thực vật là gì?', 'Sống tự dưỡng quang hợp', 'Sống dị dưỡng hoại sinh', 'Sống di chuyển', 'Sống cố định', 1, 40000),
(240, 12, 'Trung tâm tài chính lớn nhất nước Đức nằm ở thành phố nào?', 'Hamburg', 'Frankfurt', 'Bremen', 'Munich', 2, 40000),
(241, 12, 'Núi Ngũ Hành Sơn ở Đà Nẵng được đặt tên vào thời vua nào?', 'Nhà Lý', 'Nhà Nguyễn', 'Nhà Thanh', 'Nhà Đinh', 2, 40000),
(242, 12, 'Quốc gia nào có thị trường chứng khoán lớn thứ 2 thế giới?', 'Mỹ', 'Nhật Bản', 'Trung Quốc', 'Đức', 2, 40000),
(243, 12, 'Bức tượng bà đầm xoè là tên người dân Hà Nội thường gọi một bản sao của tượng nào?', 'Tượng Vệ nữ thành Milo', 'Thần Hera', 'Nữ thần tự do', 'Thần Gaia', 3, 40000),
(244, 12, 'Quốc hiệu nhà nước ta Việt Nam có từ thời Nguyễn Ánh năm nào?', '1802', '1803', '1804', '1805', 3, 40000),
(245, 12, 'Huyện Diễn Châu trực thuộc tỉnh nào của nước ta?', 'Nghệ An', 'Thanh Hoá', 'Quảng Trị', 'Hà Tĩnh', 1, 40000),
(246, 12, 'Điều khiển từ xa được phát minh vào năm nào?', '1918', '1898', '1788', '1828', 3, 40000),
(247, 12, 'Quốc gia nào đã tổ chức Thế vận hội mùa đông năm 1976?', 'Canada', 'Nam Tư', 'Hoa Kỳ', 'Áo', 4, 40000),
(248, 12, 'Điểm đặc trưng nhất của sinh vật trong giới nấm là gì?', 'Sống tự dưỡng quang hợp', 'Sống dị dưỡng hoại sinh', 'Sống di chuyển', 'Sống cố định', 2, 40000),
(249, 12, 'Cây cầu dài thứ 2 châu Âu nằm ở quốc gia nào?', 'Anh', 'Đức', 'Bồ Đào Nha', 'Pháp', 3, 40000),
(250, 12, 'Núi Ngũ Hành Sơn ở Đà Nẵng được vua Minh Mạng nhà Nguyễn đặt tên vào thế kỷ nào?', 'Thế kỷ XII', 'Thế kỷ XIII', 'Thế kỷ XIV', 'Thế kỷ XV', 3, 40000),
(251, 12, 'Lò vi sóng còn gọi là lò vi ba có mặt trên thị trường vào năm nào?', '1984', '1956', '1800', '1967', 4, 40000),
(252, 12, 'Triều đại nhà Nguyễn bắt đầu từ năm nào?', '1802', '1790', '1845', '1860', 1, 40000),
(253, 13, 'Đường sắt Bắc Nam không đi qua tỉnh nào trong các tỉnh nào sau đây?', 'Ninh Thuận', 'Bình Thuận', 'Đồng Nai', 'Lâm Đồng', 4, 60000),
(254, 13, 'Hiệp định Chính phủ Pháp còn được gọi là nền Cộng hoà thứ mấy?', '2', '3', '4', '5', 4, 60000),
(255, 13, 'Ở vòng cực Nam, ngày duy nhất dài 24h là?', '21-03', '22-06', '23-09', '22-12', 4, 60000),
(256, 13, 'Đóng gói, chế biến và phân phối sản phẩm là chức năng của?', 'Lục lạp', 'Ty thể', 'Bộ máy Golgi', 'Lưới nội chất', 3, 60000),
(257, 13, 'Hợp chất đóng vai trò quan trọng nhất trong sinh sản và di truyền là?', 'Protein', 'Axit nucleic', 'Gluxit', 'Lipit', 2, 60000),
(258, 13, 'Trong lịch sử tổ chức các đơn vị hành chính ở Việt Nam, cấp tỉnh xuất hiện từ khi nào?', '1658', '1831', '1900', '1945', 2, 60000),
(259, 13, 'Cuộc khởi nghĩa nông dân tiêu biểu nhất ở thế kỷ XVI là?', 'Tây Sơn', 'Trần Cảo', 'Trần Tuân', 'Lê Hy, Trịnh Hưng', 2, 60000),
(260, 13, 'Ai là cha đẻ của ngành vi sinh học?', 'Edward Jenner', 'Louis Pasteur', 'Hippocrates', 'Alexandre Yersin', 2, 60000),
(261, 13, 'Chiến thắng có ý nghĩa lớn lao của nghĩa quân Tây Sơn ở Đàng Trong năm 1875 là chiến thắng gì?', 'Hạ thành Quy Nhơn', 'Chiếm đất Gia Định', 'Đánh bại quân Xiêm', 'Giải phóng Quảng Ninh', 3, 60000),
(262, 13, 'Đường biển từ Hải Phòng đi Hồng Kông dài khoảng bao nhiêu kilômet?', '90Km', '900Km', '100Km', '1000Km', 2, 60000),
(263, 13, 'Ai là người sáng lập ra học thuyết về chủ nghĩa xã hội khoa học?', 'Aristotle', 'Karl Marx', 'Voltaire', 'Vladimir Lenin', 2, 60000),
(264, 13, 'Khoảng cách mỗi múi giờ rộng khoảng bao nhiêu?', '5 độ kinh tuyến', '10 độ kinh tuyến', '15 độ kinh tuyến', '20 độ kinh tuyến', 3, 60000),
(265, 13, 'Cấu trúc của phân tử protein có thể bị biến tính bởi?', 'Nước', 'Nhiệt độ', 'Cacbonic', 'Oxi', 2, 60000),
(266, 13, 'Tự sao chép ADN của sinh vật nhân chuẩn được sao chép như thế nào?', 'Một vòng sao chép', 'Hai vòng sao chép', 'Nhiều vòng sao chép', 'Dạng mạch thẳng', 3, 60000),
(267, 13, 'Ai được mệnh danh là ông tổ ngành quân giới Việt Nam?', 'Cao Thắng', 'Phan Đình Phùng', 'Hồ Tùng Dậu', 'Võ Nguyên Giáp', 1, 60000),
(268, 13, 'Xã hội phong kiến Pháp trước cách mạng có mấy đẳng cấp?', '4 đẳng cấp', '3 đẳng cấp', '2 đẳng cấp', 'Không có đẳng cấp', 2, 60000),
(269, 13, 'NATO là tên viết tắt thông dụng của Tổ chức Hiệp ước Bắc Đại Tây Dương, lực lượng này ban đầu là do nước nào thành lập?', 'Anh Mỹ', 'Nga Mỹ', 'Anh Nga', 'Canada Mỹ', 4, 60000),
(270, 13, 'Tác giả của bộ Thượng Kinh ký sự, nhà y học lỗi lạc của Việt Nam thế kỷ XVIII là ai?', 'Tuệ Tĩnh', 'Ngô Nhân Danh', 'Lê Quý Đôn', 'Lê Hữu Trác', 4, 60000),
(271, 13, 'Đường biển từ Hải Phòng đi Đà Nẵng dài khoảng bao nhiêu kilômet?', '100Km', '500Km', '1000Km', '5000Km', 2, 60000),
(272, 13, 'Lã Thượng là tên gọi khác của nhân vật lịch sử nào của Trung Quốc?', 'Khổng Tử', 'Lão Tử', 'Mạnh Tử', 'Khương Tử Nha', 4, 60000),
(273, 13, 'Con sông nào không phải sông ở Nam Bộ?', 'Sông Tiền', 'Sông Hậu', 'Sông Đà Rằng', 'Sông Sài Gòn', 3, 60000),
(274, 14, 'Khối lượng của mặt trời vào khoảng bao nhiêu?', '2 tỉ tấn', '2 tỉ tỉ tấn', '20 tỉ tấn', '20 tỉ tỉ tấn', 2, 85000),
(275, 14, 'Vị hoàng đế cuối cùng bị lật đổ và Trung Quốc trở thành nước cộng hoà vào năm nào?', '1908', '1909', '1910', '1911', 4, 85000),
(276, 14, 'Quốc gia nào dành nhiều thời gian cho việc ăn uống nhất thế giới?', 'Somalia', 'Hoa Kỳ', 'Cuba', 'Thổ Nhĩ Kỳ', 4, 85000),
(277, 14, 'Ngày 22/10 là quốc khánh của quốc gia nào sau đây?', 'Venezuela', 'Vanuatu', 'Vatican', 'Việt Nam', 2, 85000),
(278, 14, 'Ngày 06/06 là quốc khánh của quốc gia nào sau đây?', 'Hà Lan', 'Phần Lan', 'Thuỵ Điển', 'Na Uy', 3, 85000),
(279, 14, 'Ngày 01/07 là quốc khánh của quốc gia nào sau đây?', 'Uganda', 'Rwanda', 'Hungary', 'Bulgary', 2, 85000),
(280, 14, 'Ngày 15/09 là quốc khánh của quốc gia nào sau đây?', 'Namibia', 'Nepal', 'Niger', 'Nicaragua', 4, 85000),
(281, 14, 'Ngày 21/09 là quốc khánh của quốc gia nào sau đây?', 'Mali', 'Malta', 'Malaysia', 'Moldova', 2, 85000),
(282, 14, 'Khối lượng của mặt trời gấp khoảng bao nhiêu lần khối lượng trái đất?', '333.000 lần', '333.000.000 lần', '333 lần', '333 tỉ lần', 1, 85000),
(283, 14, 'Theo Phong Thuỷ, trong các kiến trúc sau. Kiến trúc nào sẽ đem lại điềm gở?', 'Các cửa xoay vòng', 'Các gác tròn', 'Các sân tròn', 'Các cột chống vuông', 4, 85000),
(284, 14, 'Người dân quốc gia nào hút thuốc lá nhiều nhất thế giới?', 'Hy Lạp', 'Cuba', 'Yemen', 'Nam Phi', 1, 85000),
(285, 14, 'Ngày 30/07 là quốc khánh của quốc gia nào sau đây?', 'Vatican', 'Vanuata', 'Venezuela', 'Việt Nam', 2, 85000),
(286, 14, 'Ngày 25/11 là quốc khánh của quốc gia nào sau đây?', 'Sudan', 'Syria', 'Sri Lanka', 'Suriname', 4, 85000),
(287, 14, 'Ngày 12/06 là quốc khánh của quốc gia nào sau đây?', 'Anh', 'Đức', 'Nga', 'Pháp', 3, 85000),
(288, 14, 'Ngày 06/02 là quốc khánh của quốc gia nào sau đây?', 'Nicaragua', 'Namibia', 'New Zealand', 'Niger', 3, 85000),
(289, 14, 'Ngày 16/09 là quốc khánh của quốc gia nào sau đây?', 'Moldova', 'Mexico', 'Mông Cổ', 'Mozambique', 2, 85000),
(290, 14, 'Trọng lượng của mặt trời gấp khoảng bao nhiêu lần trọng lượng trái đất?', '17 lần', '18 lần', '27 lần', '28 lần', 4, 85000),
(291, 14, 'Tính đến thời điểm năm 2010, chiếc cầu nào là cầu dài nhất thế giới?', 'Cầu San Mateo Haywards', 'Cầu Donghai', 'Cầu Chesapeake', 'Cầu Vasco da Gama', 2, 85000),
(292, 14, 'Quốc gia nào có tỷ lệ tử vong nhiều nhất thế giới?', 'Zimbabwe', 'Somalia', 'Afganistan', 'Mông Cổ', 3, 85000),
(293, 14, 'Ngày 01/09 là quốc khánh của quốc gia nào sau đây?', 'Uzbekistan', 'Uruguay', 'Uganda', 'Ukraine', 1, 85000),
(294, 14, 'Ngày 01/01 là quốc khánh của quốc gia nào sau đây?', 'Sri Lanka', 'Sudan', 'Syria', 'Singapore', 2, 85000),
(295, 15, 'Bạn hãy cho biết mức chở tối đa của xe đạp thồ là bao nhiêu?', '252Kgchuyến', '152 kgchuyến', '352Kgchuyến', '452Kgchuyến', 3, 150000),
(296, 15, 'Georgetown là thủ đô của quốc gia nào?', 'Guyana', 'Ghana', 'Gabong', 'Goergia', 1, 150000),
(297, 15, 'Vua Quang Trung đã đánh tan 29 vạn quân Thanh vào năm nào?', '1600', '1789', '1801', '1812', 2, 150000),
(298, 15, 'Karaoke do ông Inoue Daisuke người Nhật phát minh vào năm 1971, khi đó ông bao nhiêu tuổi?', '31', '32', '33', '34', 1, 150000),
(299, 15, 'Bộ luật ban hành dưới triều Nguyễn là luật gì?', 'Luật Hình thư', 'Luật Hồng Đức', 'Hoàng triều luật lệ', 'Quốc triều hình luật', 3, 150000),
(300, 15, 'Ai là người giải thích sự hình thành của Cacbon 14?', 'W. F. Libby', 'Lomoloxop', 'Dalton', 'Boile', 1, 150000),
(301, 15, 'Portauprince là thủ đô của quốc gia nào?', 'Honduras', 'Hungary', 'Haiti', 'Hongkong', 3, 150000),
(302, 15, 'Tuyên ngôn Nhân quyền và Dân quyền 08/1789 và Hiến pháp 1791 ở Pháp phục vụ chủ yếu cho quyền lợi của giai cấp và tầng lớp nào?', 'Tư sản', 'Vô sản', 'Tiểu tư sản', 'Tăng lữ', 1, 150000),
(303, 15, 'Pin được phát minh vào năm nào?', '1700', '1750', '1800', '1850', 3, 150000),
(304, 15, 'Tegucigalpa là thủ đô của quốc gia nào?', 'Hongkong', 'Honduras', 'Haiti', 'Hungary', 2, 150000),
(305, 15, 'Cách mạng tư sản Anh giữa thế kỷ XVII đem lại quyền lợi cho?', 'Nhân dân lao động', 'Quý tộc cũ', 'Giai cấp tư sản và quý tộc mới', 'Vua nước Anh', 3, 150000),
(306, 15, 'Điện thoại là một thiết bị viễn thông dùng để truyền và nhận âm thanh thông dụng nhất là truyền giọng nói từ xa được phát minh vào năm?', '1876', '1895', '1910', '1920', 1, 150000),
(307, 15, 'Guatemala là thủ đô của quốc gia nào?', 'Guatemala', 'Guam', 'Ghana', 'Gabong', 1, 150000),
(308, 15, 'Bình Tây Đại nguyên soái là danh hiệu nhân dân phong cho thủ lĩnh nào?', 'Trương Định', 'Nguyễn Hữu Huân', 'Nguyễn Trung Trực', 'Võ Duy Dương', 1, 150000),
(309, 15, 'Máy rút tiền tự động được phát minh vào năm nào?', '1992', '1980', '1967', '1950', 3, 150000),
(310, 15, 'Liên minh Việt Miên Lào được thành lập vào ngày tháng năm nào?', '11/3/1951', '3/3/1951', '13/3/1951', '21/3/1951', 1, 150000),
(311, 15, 'Trên bán cầu Nam thì cực giá lạnh nằm gần trạm nam cực Saiudơ gần Vostok, nơi này đã ghi nhận được nhiệt thấp 83 độ C vào ngày nào?', '21/07/1983', '12/07/1983', '01/07/1983', '23/07/1983', 1, 150000),
(312, 15, 'Lời nói thật là cách xã giao tốt nhất là câu nói của ai?', 'Tourgeunev', 'B Montesquieu', 'Virgile', 'Kant', 1, 150000),
(313, 15, 'Trên bán cầu Bắc thì cực giá lạnh nằm tại miền Siberia, gần Tp. Oymyakon, nơi có nhiệt độ thấp nhất -77 độ C, được ghi nhận vào ngày nào?', '12/01/1938', '26/02/1938', '26/01/1938', '05/01/1938', 3, 150000),
(314, 15, 'Đau khổ vì yêu, dù sao cũng dễ chịu hơn là thiếu tình yêu là câu nói của ai?', 'Tourgeunev', 'Virgile', 'O.S. Warden', 'Krassovsky', 4, 150000),
(315, 15, 'Nhiệt độ cao nhất trên thế giới được ghi nhận ở đâu?', 'Thung lũng California', 'Sa mạc Sahara', 'Sa mạc Lybia', 'Sa mạc Gobi', 3, 150000);

-- Chỉ mục cho các bảng

-- Chỉ mục cho bảng `account`

ALTER TABLE `account`
  ADD PRIMARY KEY (`id`);

-- Chỉ mục cho bảng `questions`

ALTER TABLE `questions`
  ADD PRIMARY KEY (`id`);

-- AUTO_INCREMENT cho các bảng đã đổ

-- AUTO_INCREMENT cho bảng `account`

ALTER TABLE `account`
  MODIFY `id` int NOT NULL AUTO_INCREMENT, AUTO_INCREMENT=4;

-- AUTO_INCREMENT cho bảng `questions`

ALTER TABLE `questions`
  MODIFY `id` int NOT NULL AUTO_INCREMENT, AUTO_INCREMENT=4273;
COMMIT;


